build:
  image: ensime/ensime:latest
  pull: true
  environment:
    - SCALA_VERSION=2.11.7
  commands:
    - git log --format="%h : %an : %s" --graph --max-count=5 ;
      cask pkg-file ;
      cask install ;
      cask build ;
      test/run_emacs_tests.sh ;
      if [ -n "$UNDERCOVER" ] && [ -f "coveralls.json" ] ; then
        curl -v -include --form json_file=@coveralls.json https://coveralls.io/api/v1/jobs || true ;
      fi

matrix:
  EMACS:
    - /opt/emacs-24.5/bin/emacs
