pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    privileged: true
    environment:
      - SBT_VOLATILE_TARGET=/root/ramdisk
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - mkdir -p $SBT_VOLATILE_TARGET && mount -t tmpfs -o size=1g tmpfs $SBT_VOLATILE_TARGET ; df -h
      - cask pkg-file ;
        cask install ;
        cask package ;
      - cask exec ert-runner ;
      - cask exec ecukes ;
      - cd test/example ; sbt ensimeConfig ; cd ../.. ;
      - test/run_emacs_tests.sh || test/run_emacs_tests.sh ;
